<?php

declare(strict_types=1);

/**
 * PHPUnit Bootstrap
 *
 * This file runs ONCE before all tests to:
 * 1. Load the autoloader
 * 2. Verify index.json exists (generated by bin/run.sh)
 * 3. Define path constants for tests
 *
 * NOTE: Index generation is handled by bin/run.sh BEFORE tests run.
 * Tests only read and validate the pre-generated index.json.
 */

require_once __DIR__ . '/../vendor/autoload.php';

// Load configuration
$config = require __DIR__ . '/../config.php';

// Resolve output directory path
$contractTestsDir = dirname(__DIR__);
$outputDir = $config['output_dir'];
if (!str_starts_with($outputDir, '/')) {
    $outputDir = $contractTestsDir . '/' . $outputDir;
}

// Build index.json path
$indexJsonPath = $outputDir . '/' . ($config['index_json'] ?? 'index.json');

// Verify index.json exists
if (!file_exists($indexJsonPath)) {
    throw new RuntimeException(
        sprintf(
            "index.json not found at: %s\n" .
            "Run tests via bin/run.sh which generates the index first:\n" .
            "  ./bin/run.sh test",
            $indexJsonPath
        )
    );
}

echo sprintf("Using index: %s\n", $indexJsonPath);

// Store index.json path for tests
// CallsData can load directly from index.json (it ignores the scip key)
define('INDEX_JSON_PATH', $indexJsonPath);
define('CALLS_JSON_PATH', $indexJsonPath);

// ScipData loads from the same unified file
define('SCIP_JSON_PATH', $indexJsonPath);
