<?php

declare(strict_types=1);

/**
 * PHPUnit Bootstrap
 *
 * This file runs ONCE before all tests to:
 * 1. Load the autoloader
 * 2. Verify calls.json exists (generated by bin/run.sh)
 * 3. Define the CALLS_JSON_PATH constant for tests
 *
 * NOTE: Index generation is handled by bin/run.sh BEFORE tests run.
 * Tests only read and validate the pre-generated calls.json.
 */

require_once __DIR__ . '/../vendor/autoload.php';

// Load configuration
$config = require __DIR__ . '/../config.php';

// Resolve output directory path
$contractTestsDir = dirname(__DIR__);
$outputDir = $config['output_dir'];
if (!str_starts_with($outputDir, '/')) {
    $outputDir = $contractTestsDir . '/' . $outputDir;
}

// Build calls.json path
$callsJsonPath = $outputDir . '/' . $config['calls_json'];

// Verify calls.json exists
if (!file_exists($callsJsonPath)) {
    throw new RuntimeException(
        sprintf(
            "calls.json not found at: %s\n" .
            "Run tests via bin/run.sh which generates the index first:\n" .
            "  ./bin/run.sh test",
            $callsJsonPath
        )
    );
}

echo sprintf("Using index: %s\n", $callsJsonPath);

// Store calls.json path for tests
define('CALLS_JSON_PATH', $callsJsonPath);

// Build SCIP JSON path (optional - may not exist)
$scipJsonPath = $outputDir . '/' . ($config['scip_json'] ?? 'index.scip.json');
if (file_exists($scipJsonPath)) {
    echo sprintf("Using SCIP index: %s\n", $scipJsonPath);
    define('SCIP_JSON_PATH', $scipJsonPath);
}
