<?php

declare(strict_types=1);

namespace ContractTests\Tests;

use ContractTests\Attribute\ContractTest;
use ContractTests\CallsContractTestCase;

/**
 * Smoke tests to validate the entire contract testing flow.
 */
class SmokeTest extends CallsContractTestCase
{
    /**
     * Verifies calls.json was generated by bootstrap.php during test initialization.
     * This is the first test to run and validates the index generation pipeline works.
     */
    #[ContractTest(
        name: 'Index Generated',
        description: 'Verifies calls.json was generated by bootstrap.php during test initialization',
        category: 'smoke',
    )]
    public function testIndexWasGenerated(): void
    {
        $this->assertFileExists(CALLS_JSON_PATH, 'calls.json should be generated by bootstrap');
    }

    /**
     * Verifies CallsData wrapper loaded calls.json successfully.
     * Checks that both values and calls arrays are non-empty.
     */
    #[ContractTest(
        name: 'Calls Data Loaded',
        description: 'Verifies CallsData wrapper loaded calls.json successfully with non-empty values and calls arrays',
        category: 'smoke',
    )]
    public function testCallsDataLoaded(): void
    {
        $this->assertNotNull(self::$calls, 'CallsData should be loaded');
        $this->assertGreaterThan(0, self::$calls->valueCount(), 'Should have values');
        $this->assertGreaterThan(0, self::$calls->callCount(), 'Should have calls');
    }

    /**
     * Critical acceptance test for the contract testing framework.
     *
     * Code reference: src/Repository/OrderRepository.php:26
     *   public function save(Order $order): Order
     *
     * Expected: A value entry exists with:
     *   - kind: parameter
     *   - symbol containing: OrderRepository#save().($order)
     *   - type containing: Order
     */
    #[ContractTest(
        name: 'OrderRepository::save() $order Parameter',
        description: 'Critical acceptance test: Verifies $order parameter in OrderRepository::save() exists in index with kind=parameter, symbol containing ($order), and type containing Order',
        category: 'smoke',
    )]
    public function testOrderRepositorySaveParameterExists(): void
    {
        $values = $this->values()
            ->kind('parameter')
            ->symbolContains('OrderRepository#save().($order)')
            ->all();

        $this->assertNotEmpty(
            $values,
            'Should find value entry for $order parameter in OrderRepository::save(). ' .
            'Reference: src/Repository/OrderRepository.php:26'
        );

        $orderParam = $values[0];
        $this->assertEquals('parameter', $orderParam['kind']);
        $this->assertStringContainsString('($order)', $orderParam['symbol']);
        $this->assertNotNull($orderParam['type'] ?? null, 'Parameter should have type');
        $this->assertStringContainsString('Order', $orderParam['type']);
    }

    /**
     * Verifies calls.json contains a valid semver-like version field.
     * Example: "3.2"
     */
    #[ContractTest(
        name: 'Version Present',
        description: 'Verifies calls.json contains a valid semver-like version field (e.g., 3.2)',
        category: 'smoke',
    )]
    public function testVersionIsPresent(): void
    {
        $version = self::$calls->version();
        $this->assertNotEmpty($version, 'Version should be present');
        $this->assertMatchesRegularExpression('/^\d+\.\d+/', $version, 'Version should be semver-like');
    }

    /**
     * Verifies ValueQuery::kind() filter correctly returns only values matching the specified kind.
     * Tests with 'parameter' kind and verifies all results have kind=parameter.
     */
    #[ContractTest(
        name: 'Value Query Filters',
        description: 'Verifies ValueQuery::kind() filter correctly returns only values matching the specified kind (parameter)',
        category: 'smoke',
    )]
    public function testValueQueryFiltersWork(): void
    {
        $parameters = $this->values()->kind('parameter')->all();
        $this->assertNotEmpty($parameters, 'Should find parameters');

        foreach ($parameters as $param) {
            $this->assertEquals('parameter', $param['kind']);
        }
    }

    /**
     * Verifies CallQuery::kind() filter correctly returns only calls matching the specified kind.
     * Tests with 'method' kind and verifies all results have kind=method.
     */
    #[ContractTest(
        name: 'Call Query Filters',
        description: 'Verifies CallQuery::kind() filter correctly returns only calls matching the specified kind (method)',
        category: 'smoke',
    )]
    public function testCallQueryFiltersWork(): void
    {
        $methods = $this->calls()->kind('method')->all();
        $this->assertNotEmpty($methods, 'Should find method calls');

        foreach ($methods as $method) {
            $this->assertEquals('method', $method['kind']);
        }
    }
}
